FROM registry.access.redhat.com/ubi8/nodejs-18

WORKDIR /usr/src/app

COPY --chown=1001:1001 package*.json ./

RUN npm ci

# Copy app source into the container
COPY --chown=1001:1001 . .

# Build the source into JS files
RUN npm run build:ts

# Configure fastify port and host defaults
ENV FASTIFY_PORT 8080
ENV FASTIFY_ADDRESS 0.0.0.0

# Note that the container exposes services on 8080
EXPOSE 8080

CMD [ "./node_modules/.bin/fastify", "start", "-l", "info", "dist/app.js" ]